import { Platform } from 'react-native';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Subject, Topic } from './NotesData';

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function buildHtml(subject: Subject, topic: Topic): string {
  const code = topic.code
    ? `<pre style="background:#0f172a;color:#4ade80;padding:16px;border-radius:12px;font-family:Menlo,Consolas,monospace;font-size:13px;line-height:1.6;overflow-wrap:break-word;white-space:pre-wrap;">${escapeHtml(topic.code)}</pre>`
    : '';
  return `<html><head><meta charset="utf-8" /></head><body style="margin:32px;font-family:Helvetica,Arial,sans-serif;color:#111827;">
    <div style="border-bottom:3px solid #2563eb;padding-bottom:12px;margin-bottom:24px;">
      <div style="font-size:12px;color:#2563eb;font-weight:bold;letter-spacing:2px;">NOTES BY AMAN SIR</div>
      <h1 style="font-size:26px;margin:6px 0 0;">${escapeHtml(topic.title)}</h1>
      <div style="color:#6b7280;font-size:14px;margin-top:4px;">${escapeHtml(subject.title)}</div>
    </div>
    <p style="font-size:15px;line-height:1.75;color:#374151;">${escapeHtml(topic.content)}</p>
    ${code}
    <div style="margin-top:36px;padding-top:12px;border-top:1px solid #e5e7eb;color:#9ca3af;font-size:11px;">Generated by NotesByAmanSir &middot; Learn smarter, score higher.</div>
  </body></html>`;
}

export async function shareTopicPdf(subject: Subject, topic: Topic): Promise<boolean> {
  if (Platform.OS === 'web') {
    return false;
  }
  try {
    const { uri } = await Print.printToFileAsync({ html: buildHtml(subject, topic) });
    const available = await Sharing.isAvailableAsync();
    if (!available) {
      return false;
    }
    await Sharing.shareAsync(uri, {
      mimeType: 'application/pdf',
      dialogTitle: `${topic.title} - Notes By Aman Sir`,
      UTI: 'com.adobe.pdf',
    });
    return true;
  } catch {
    return false;
  }
}